### ISSUE TITLE
Home couldn´t connect to this accessory

### ISSUE THREAD

**Issue by fabian1512** [mdaskalov/homebridge-dreambox#11]
In my first setup everything went well, great plugin.
Some days later I noticed, that my dm900 could not be reached by home-app.

I deleted it from HomeKit and tried to set it up again. 
"Home couldn´t connect to this accessory"

I tried to:
1. deleted dm900 in config-ui-settings 
2. reinstall plugin via config-ui
3. chmod 755 on AccessoryInfo.xyz.json (per default it is 644)
4. reinstalled homebridge

nothing works. accessory always receives the same mac-adress und home cannot connect.

in config-ui/accessories I can see the button for the dm900 and it can be executed for switch on/off

**Comment by mdaskalov** [comment]
The dreambox device should be added as separate device after Homebridge and all configured devices are added in the home app. If your dreambox is not shown as new device (after the Homebridge device is added)  try to add it by entering the code manually.

If nothing else helps try to reset Homebridge in config-ui-x and configure everything from scratch. Also delete the previous Homebridge in the home app. The config ui x plugin generates a new random code each time the Homebridge is reset. The same code should be used to add the dreambox device after the Homebridge device is added.

**Comment by fabian1512** [comment]
Thank you for your quick reply.
The problem is not, that Homebridge and dm900 are not shown up.

The HB has already been set up with a number of items. I don't want to reconfigure them with all items.
the dm900 is always displayed in homekit and asks for the code. then the connection fails.
In addition to the different rights from the AccessoryInfo.xyz.json and the IdentifierCache.xyz.json, I also noticed that in the AccessoryInfo.xyz.json the pairedClients and pairedClientsPermission do not contain any values (which is probably due to the missing connection).
The dm900 also receives the same mac address after each uninstall and installation.
Could it be that everything is not completely deleted after the deinstallation (and yes, I always delete it in config-ui-settings)

**Comment by mdaskalov** [comment]
I just deleted my configured dreambox from the home app and then reconfigured it again without any problems. The device was shown and I was able to add it to the home app.
After deletion the `pairedClients` and `pairedClientsPermission` were also empty. Then after addition, they got values.
Seems that the issue is between your phone and HB... There could be problems if IP6 is enabled on the machine where HB is installed.

Maybe there is a conflict. Do you have any other TV accessory devices configured in HB?

...if nothing else works you will have to reset and reinstall...

**Comment by fabian1512** [comment]
I´ve tried:
1. uninstalled "homebridge-denon-tv" (TV accessory devices)
2. deleted my wife´s account from HK
3. deactivated ATV and HomePod as control center
4. deactivated IP6 on Raspi
5. deleted and reinstalled your plugin
6. restarted HB each time 1-5

...still the same result. 

7. reinstalled "homebridge-denon-tv" and I was able to connect without problems in HK

So I don't think it deals with my phone/HB. Do you have any other ideas?

**Comment by mdaskalov** [comment]
I will look how this plugin handles the tv appliance connection and compare it with my implementation. Will let you know if there is a difference so you can try. 
Besides reinstalling everything I have no other ideas. Please let me know if you manage to solve it in some other way.

**Comment by fabian1512** [comment]
I have:
1. Reset and reinstalled my HK
2. Reset HB via config-ui
3. Deleted cache via config-ui

during reconnection of every accessory each of them went in HK very well. 
Even your Plugin shows still the same error.

If you need any logs from my HB, let me know

**Comment by mdaskalov** [comment]
I pushed an updated release v0.4.7. Now I initialize it the same way as in the denon plugin and I am curios if this will solve your problem. Please let me know.
The denon plugin implements a speaker service but I don't know how to use it. I really don't get what "Speaker control is possible after You go to RC app on iPhone/iPad Speaker Service" mean. Does this work for you? I could implement it in my plugin if it works nice.

**Comment by fabian1512** [comment]
I´m sorry, but your improvement didn't help. After Installation via config-ui, I got this in my log:
HAP-NodeJS WARNING: The accessory 'Dreambox' is getting published with the characteristic 'Manufacturer' (of the AccessoryInformation service) not having a value set. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
HAP-NodeJS WARNING: The accessory 'Dreambox' is getting published with the characteristic 'Model' (of the AccessoryInformation service) not having a value set. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
HAP-NodeJS WARNING: The accessory 'Dreambox' is getting published with the characteristic 'SerialNumber' (of the AccessoryInformation service) not having a value set. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
HAP-NodeJS WARNING: The accessory 'Dreambox' is getting published with the characteristic 'FirmwareRevision' (of the AccessoryInformation service) not having a value set. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
[6/14/2020, 3:39:22 PM] Dreambox is running on port 43891.

**Comment by mdaskalov** [comment]
Seems, that you have cached accessory, which is screwed up. I also noticed problems when you reboot. So I will try to remove all cached accessories as it's done in the harmony plugin. maybe this could help. Will let you know when I am ready.

**Comment by fabian1512** [comment]
As I wrote before, I deleted all cached Accessoires, what didn't help.

If you give me a hint (link or something), I can learn how to test a branch

**Comment by mdaskalov** [comment]
I rolled back (some of) the changes, as I got a sub device for each channel on HB reboot. Will try to implement it as in the harmony plugin with cache cleanup in next release.

**Comment by fabian1512** [comment]
As expected:
in HB on my Mac, plugin works properly, even after several reinstalls.

in HB on Raspi, still the same result. I assume, there must be some data left somewhere.
I checked the cachedAccessories, there is only data from the plugin "washingmachine POW"
