### ISSUE TITLE
Bouquet is not a fuction

### ISSUE THREAD

**Issue by JoMensdorf** [mdaskalov/homebridge-dreambox#14]
Hi!

I try to use homebridge-dreambox v0.4.8  with my homebridge 1.1.1 and a ET9200 with an old openatv 4.2.1 on port 80 witout a password protection.
I have only one Bouqet called "HD" and get that message:
[7/21/2020, 21:33:23] [Dreambox] TypeError: res.e2servicelistrecursive.e2bouquet.find is not a function
    at /usr/local/lib/node_modules/homebridge-dreambox/dreambox-accessory.js:188:62
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

 {
            "devices": [
                {
                    "name": "Wohnzimmer",
                    "hostname": "192.168.178.40",
                    "port": 80,
                    "bouquet": "HD"
                }
            ],
            "platform": "Dreambox"
        }

Can you tell me what´s wrong?

Thanks,
Jo

**Comment by mdaskalov** [comment]
Seems that the call `getallservices` doesn't return an array with bouquets. I will include a check in the next release.

could you please check what is returned when you call following url (you can use curl or call it directly it in a browser)

`http://192.168.178.40/web/getallservices`

you should get get xml with all bouquets [this](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/wiki/OpenWebif-API-documentation#getallservices).

**Comment by JoMensdorf** [comment]
That what I get here http://192.168.178.40/web/getallservices :

`<e2servicelistrecursive>
<e2bouquet>
<e2servicereference>
1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.favourites.tv" ORDER BY bouquet
</e2servicereference>
<e2servicename>HD</e2servicename>
<e2servicelist>
<e2service>
<e2servicereference>1:0:19:283D:3FB:1:C00000:0:0:0:</e2servicereference>
<e2servicename>Das Erste HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:2B66:3F3:1:C00000:0:0:0:</e2servicereference>
<e2servicename>ZDF HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:2856:401:1:C00000:0:0:0:</e2servicereference>
<e2servicename>BR Fernsehen Nord HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:EF10:421:1:C00000:0:0:0:</e2servicereference>
<e2servicename>RTL HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:EF74:3F9:1:C00000:0:0:0:</e2servicereference>
<e2servicename>SAT.1 HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:EF75:3F9:1:C00000:0:0:0:</e2servicereference>
<e2servicename>ProSieben HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:EF11:421:1:C00000:0:0:0:</e2servicereference>
<e2servicename>VOX HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:EF76:3F9:1:C00000:0:0:0:</e2servicereference>
<e2servicename>kabel eins HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:283E:3FB:1:C00000:0:0:0:</e2servicereference>
<e2servicename>arte HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:EF15:421:1:C00000:0:0:0:</e2servicereference>
<e2servicename>RTLII HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:2B8E:3F2:1:C00000:0:0:0:</e2servicereference>
<e2servicename>3sat HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:EF77:3F9:1:C00000:0:0:0:</e2servicereference>
<e2servicename>SIXX HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:2B98:3F2:1:C00000:0:0:0:</e2servicereference>
<e2servicename>KiKA HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:EF78:3F9:1:C00000:0:0:0:</e2servicereference>
<e2servicename>Pro7 MAXX HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:157F:41F:1:C00000:0:0:0:</e2servicereference>
<e2servicename>Deluxe Music HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:2777:409:1:C00000:0:0:0:</e2servicereference>
<e2servicename>MTV HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:30D6:413:1:C00000:0:0:0:</e2servicereference>
<e2servicename>Eurosport 1 HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:30D7:413:1:C00000:0:0:0:</e2servicereference>
<e2servicename>Eurosport 2 HD Xtra</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:1581:41F:1:C00000:0:0:0:</e2servicereference>
<e2servicename>SPORT1 HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:6C:C:85:C00000:0:0:0:</e2servicereference>
<e2servicename>Sky Sport News HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:EF14:421:1:C00000:0:0:0:</e2servicereference>
<e2servicename>n-tv HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:5274:41D:1:C00000:0:0:0:</e2servicereference>
<e2servicename>WELT HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:1:30:5:85:C00000:0:0:0:</e2servicereference>
<e2servicename>N24 DOKU</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:19:2887:40F:1:C00000:0:0:0:</e2servicereference>
<e2servicename>tagesschau24 HD</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:1:6DCA:44D:1:C00000:0:0:0:</e2servicereference>
<e2servicename>Das Erste</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:1:6D66:437:1:C00000:0:0:0:</e2servicereference>
<e2servicename>ZDF</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:1:2EE6:441:1:C00000:0:0:0:</e2servicereference>
<e2servicename>RTL FS</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:1:4463:453:1:C00000:0:0:0:</e2servicereference>
<e2servicename>SAT.1 Bayern</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:1:445D:453:1:C00000:0:0:0:</e2servicereference>
<e2servicename>ProSieben</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:1:2F1C:441:1:C00000:0:0:0:</e2servicereference>
<e2servicename>VOX</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:1:445E:453:1:C00000:0:0:0:</e2servicereference>
<e2servicename>kabel eins</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:1:7034:41B:1:C00000:0:0:0:</e2servicereference>
<e2servicename>arte</e2servicename>
</e2service>
<e2service>
<e2servicereference>1:0:1:4460:453:1:C00000:0:0:0:</e2servicereference>
<e2servicename>SAT.1 Gold</e2servicename>
</e2service>
</e2servicelist>
</e2bouquet>
</e2servicelistrecursive>`

**Comment by mdaskalov** [comment]
Funny! It's not an array, because you have only one bouquet, right?
Seems that I have to implement the case when only one bouquet is returned.

**Comment by JoMensdorf** [comment]
Yes, I only have one. My wife would get into the wrong one and won´t be able to switch back ;-)
Would be great if that could be implemented.
Thanks a lot!
Jo

**Comment by mdaskalov** [comment]
I've just published new version in which the problem (hopefully) is solved. 
Could you please test and let me know.

**Comment by JoMensdorf** [comment]
That works. Great!
Thanks a lot!!!!!!

Cheers, Jo
