### ISSUE TITLE
Doesn't work with Dreambox One

### ISSUE THREAD

**Issue by MaTr75** [mdaskalov/homebridge-dreambox#16]
i get following line in the Log-File:

[21.9.2020, 22:32:44] [Dreambox] Device: 192.168.201.159, API Call: http://192.168.201.159:80/web/powerstate?newstate=4, Error:  Unexpected close tag
Line: 53
Column: 7
Char: >

When I paste "http://192.168.201.159/web/powerstate?newstate=4" in a browser, I get an Error "405 - Invalid method: GET!
GET is not allowed here, please use POST"

Any Idea?

**Comment by mdaskalov** [comment]
It seems to me that the web interface is not available. Please try [http://IP_of_your_box/web/deviceinfo](http://IP_of_your_box/web/deviceinfo) in a browser window. 
Look at this [wiki](https://dream.reichholf.net/wiki/Enigma2:WebInterface) for reference. 
There should be a package for the web interface which is not installed by default.

**Comment by MaTr75** [comment]
The Web IF is available

![F256FED7-1A62-4FE7-BC76-599D6FA237FD](https://user-images.githubusercontent.com/62939456/93847164-753e2880-fca6-11ea-9df1-2d74c27719a4.png)

**Comment by mdaskalov** [comment]
Does the link [http://dreambox/web/powerstate](http://dreambox/web/powerstate) work?
What comes back?

**Comment by MaTr75** [comment]
![Uploading 39FD7951-22C8-44F6-858F-738A7402608B.jpeg…]()

I solved it... I turned the anti-hijacking off... now ist works...

**Comment by mdaskalov** [comment]
Okay I will write it in the README file. Thanx
