### ISSUE TITLE
Device category Audio/video receiver instead of television

### ISSUE THREAD

**Issue by eloy83** [mdaskalov/homebridge-dreambox#21]
I just saw that Homekit has a device category „Audio/video receivers“.

Instead of integrating Dreamboxes to Homekit as televisions maybe it would be possible to do this as Audio/video receivers.

**Comment by mdaskalov** [comment]
I am not sure if this is supported in homebridge. Do yo have an example plugin? 

What would be the benefit of doing so?

**Comment by eloy83** [comment]
I saw it in the wikipedia article about device categories supported by Homekit. But did not thought about the Homebridge compatibility with this (new?) device category.

The benefit I see is that when you have a Dreambox most probably you will have also a TV in the same room. The TV and the Dreambox have then the device category "TV". Telling Siri to power on/off your TV will lead to Siri asking you to specify which one because of multiple TV's in the same room.

**Comment by mdaskalov** [comment]
Seems that this is indeed possible. I found some suitable device types [here](https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/Accessory.ts) and made the category configurable in the advanced settings in my latest release.
Hope that I just earned a star...

**Comment by eloy83** [comment]
Great, thank you very much!
