### ISSUE TITLE
Static Port Assignment

### ISSUE THREAD

**Issue by WolfMa99** [mdaskalov/homebridge-dreambox#22]
Hi,

I had an issue, connecting my box in the Home App. I realized than, that the plugin is opening a port on the host. This port has to be allowed by the firewall. That isn't a real problem, I think, just one step more. But the problem occurs, when you restart the host or just home bridge as a service, than the plugin opens a new port, a different one. Than I have to reconfigure the firewall for allowing that port and removing the old one.

The question is now, what is that port used for (just for my interest, I want to learn). The more important one is, can a setting be implemented allowing to configure manually a port, that is always chosen, that option can be optional, so as a fallback the normal random generation can take place.

I hope it was understandable and thank you for your help.

Greetings Marvin
![port](https://user-images.githubusercontent.com/36261965/104854748-c97db000-5908-11eb-997e-4be681a6176b.png)

**Comment by mdaskalov** [comment]
The assigning of this port has nothing to do with my plugin. It's done by homebridge itself and as far as I know I can't control it from inside my plugin. 

However, It is possible to configure a pool of ports to be used for this in the homebridge configuration file. Look at the sample [configuration file](https://github.com/homebridge/homebridge/blob/master/config-sample.json). There is a section "ports" used exactly for what you want. If there are no defined port, a random port is used.

Hope that this helps and that my research is worth a star. ;)

**Comment by WolfMa99** [comment]
Oh ok, I now understand it. :)

That helped a lot. I configured a quite small pool of ports. After each restart the plugin now picks the lowest value of the range and that port I can configure in my firewall. Thank you really really much. Stared ;)

**Comment by mdaskalov** [comment]
Thanks!
