### ISSUE TITLE
Dreambox/ VuSolo not connectable

### ISSUE THREAD

**Issue by OberfragGER** [mdaskalov/homebridge-dreambox#23]
I see the VU-Box in Hombridge but its not possible to add in "Home". The console shows:
[2021-2-22 11:55:20] [homebridge-dreambox] This plugin generated a warning from the characteristic 'Active': SET handler returned write response value, though the characteristic doesn't support write response! See https://git.io/JtMGR for more info.
What can i do?

**Comment by mdaskalov** [comment]
I've seen these warnings in the last version of homebridge. They are not the problem. Your receiver is not responding correctly. Could you provide more information?

**Comment by OberfragGER** [comment]
Thanks for your replay. Yesterday evening i managed to get this working correctly again.

The key was to delete the device from Homekit ("Home") and also from Homebridge (Homebridge Settings/ unlinked devices and delete that). So i was able to readd the dreambox again.

But: good plugin with a correspondending icon (TV with Setupbox, incl. the whole bouquet). Thanks for yor work.
