### ISSUE TITLE
No control buttons

### ISSUE THREAD

**Issue by blackbasket** [mdaskalov/homebridge-dreambox#25]
Hi,

I started using the plugin today. I can switch channels using bouqet as well as separate switches. Changing power state works, too.

But I cannot find i.e. the volume button as noticed in the description. I tried all selectable device types.

I am using Home App.

Regards,
Marcel

**Comment by mdaskalov** [comment]
You have to use the remote control app. When started the physical volume buttons will control the Dreambox volume. You have also the most used keys (arrows, ok, menu, info and exit). If you have other devices such as Apple TV you should select Dreambox from the drop-down list.

**Comment by blackbasket** [comment]
Thank you. Understood :)

**Comment by sickboy2711** [comment]
> You have to use the remote control app. When started the physical volume buttons will control the Dreambox volume. You have also the most used keys (arrows, ok, menu, info and exit). If you have other devices such as Apple TV you should select Dreambox from the drop-down list.

Ich verstehe die Antwort nicht ganz; 
Ich habe die Standart Einstellungen vorgenommen:
`            "devices": [
                {
                    "name": "dreambox",
                    "hostname": "192.168.2.161",
                    "port": 80,
                    "bouquet": "Deutsch",
                    "channels": [
                        {
                            "name": "3 plus",
                            "ref": "1:0:1:B:1D:1D:FFFF0000:0:0:0"
                        }
                    ],
                    "updateInterval": 0,
                    "offWhenUnreachable": true
                }
            ],
            "deviceType": "TV_SET_TOP_BOX",
            "platform": "Dreambox"`
den Kanal habe ich Testweise erstellt (was auch funktioniert.
Ein-/Ausschalten geht ohne Porbleme. Auf dem Web-UI von Homebridge bekomme ich auch den Volume-Button angezeigt, nur funktioniert dieser nicht. In der Home-App bekomme ich diesen gar nicht angezeigt.

Was mache ich falsch? Wurde die Dream gerne mit Siri lauter und leiser stellen / einfach nur den Befehl absenden: schalte auf den nächsten Kanal

**Comment by mdaskalov** [comment]
Dies ist nur mit der iOS-Remote-App möglich. Ich glaube nicht, dass Siri die Lautstärke auf diese Weise steuern kann. Es wäre möglich, einen Dimmer für die Lautstärke zu definieren. Dann könnte es klappen...

**Comment by sickboy2711** [comment]
Ah ok, also kann ich mit dem Plugin die Dreambox mit Siri nur ein und ausschalten und Sender umschalten, wenn ich diese konfiguriert habe?

**Comment by blackbasket** [comment]
Ja, genau... so ist es... da die DM bei mir aber an einem AV-Receiver hängt, steure ich die Lautstärke dadrüber... bei mir ist es ein Ventilator, aber Dimmer dürfte auch funktionieren...
