### ISSUE TITLE
polling

### ISSUE THREAD

**Issue by mothabrain** [mdaskalov/homebridge-dreambox#28]
Hi! Nice plugin. what about implementing a polling interval for the tuner, to get it working again after turned off?

**Comment by mdaskalov** [comment]
You mean if the dream is not reachable? This shouldn't be a problem if the dream is already detected. 

On homebridge reboot the channels are not read, if the dream is not reachable - in this case it would make sense to retry the detection after a moment.

If you want to synchronize the on/off state or the selected channel with homebridge you can use MQTT.

**Comment by mothabrain** [comment]
my setup is a smart plug with the cable tuner connected. so when i turn on the smart plug the tuner starts to boot up. but still in the home app it remains unreachable. only if i restart the homebridge server the tuner gets the tuners state. i haven't implemented mqtt at the moment, but i have a a denon a/v receiver which works flawless with the homebridge polling the power state directly every 3 seconds.

**Comment by mdaskalov** [comment]
MQTT will not help if you switch off the Dreambox.
Which plugin do you use for your denon receiver? 

I think that polling each 3s will keep the homebridge busy...

I can make it optional so it can be enabled when needed.

**Comment by mothabrain** [comment]
it's this plugin:
https://github.com/grzegorz914/homebridge-denon-tv#readme

i'm running several plugins which poll their states with even lower interval (1 sec) and it's not a hit on the system performance at all (4% average cpu idle). i'm running a rpi2b even with pihole enabled. would be awesome if you could implement an optional status poll for the plugin.
