### ISSUE TITLE
- getChannel: Unexpected close tag

### ISSUE THREAD

**Issue by Stonie70** [mdaskalov/homebridge-dreambox#32]
Dear Members,

i have the following problem:
after installing & configuring the homebridge-dreambox, i get the following error messages in the log:

[9/9/2021, 6:39:50 AM] [Dreambox] sat.stonie.at :- getChannel: Unexpected close tag
Line: 53
Column: 7
Char: >

and the config is the following:

{
    "devices": [
        {
            "name": "Sat-Receiver",
            "hostname": "sat.stonie.at",
            "port": 80,
            "bouquet": "Favoriten"
        }
    ],
    "platform": "Dreambox"
}

The Plugin is also not working, so what did i wrong ?

thanks for your support.

**Comment by mdaskalov** [comment]
This plugin is meant for control Dreambox receiver in your local network. It seems that the hostname in your config is for a service which is not compatible.

**Comment by Stonie70** [comment]
Hy, the Dreambox is in my local Network (the same as the Homebridge) and I have a local DNS Server for that, but anyway I have the same effect with the IP Adress:
{
    "devices": [
        {
            "name": "Sat-Receiver",
            "hostname": "192.168.20.25",
            "port": 80,
            "username": "root",
            "password": "*****",
            "bouquet": "Favorites"
        }
    ],
    "platform": "Dreambox"
}

Even with or without authentification.
Regards ..

**Comment by mdaskalov** [comment]
Then check what is coming back when you call:
http://<host>/web/getallservices
This should return a XML with all services.
If necessary use the correct username and password.

**Comment by mdaskalov** [comment]
This url should be reachable from your homebridge server. Use curl in the terminal to test it.

**Comment by Stonie70** [comment]
I get back the following Message:
412 - Precondition failed!

sessionid is missing, invalid or expired!

**Comment by mdaskalov** [comment]
That's why it's not working... You either got the wrong IP or there is no web interface installed on your dreambox.
Try to open the IP in your browser to see if the web interface of the dream will come up. The plug-in will not work if you don't get correct XML on the URL above.
What image are you using?

**Comment by Stonie70** [comment]
So basically the webinterface works:
![grafik](https://user-images.githubusercontent.com/90376181/132853716-c29a2193-5a7b-4a6d-9623-974457c08613.png)
and I use a Newnigma2 Image.

**Comment by Stonie70** [comment]
after a restart of the receiver, I get the following back with curl:
roman@atstawhome01:~$ curl http://sat.stonie.at/web/getallservices
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>412 - Precondition failed!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>

        * {
            line-height: 1.2;
            margin: 0;
        }

        html {
            color: #888;
            display: table;
            font-family: sans-serif;
            height: 100%;
            text-align: center;
            width: 100%;
        }

        body {
            display: table-cell;
            vertical-align: middle;
            margin: 2em auto;
        }

        h1 {
            color: #555;
            font-size: 2em;
            font-weight: 400;
        }

        p {
            margin: 0 auto;
            width: 280px;
        }

        @media only screen and (max-width: 280px) {

            body, p {
                width: 95%;
            }

            h1 {
                font-size: 1.5em;
                margin: 0 0 0.3em;
            }

        }

    </style>
</head>
<body>
    <h1>412 - Precondition failed!</h1>
    <p>sessionid is missing, invalid or expired!</p>
</body>
</html>


But still not working and the same error message in Log.

**Comment by mdaskalov** [comment]
Seems that you've enabled "Token-basierte Sicherheit" (last option in Einstellungen / Netzwerk / Webinterface).

I was able to reproduce it. Please disable it. 

Try switching off other security settings if this doesn't help.

**Comment by Stonie70** [comment]
Thanks a lot, that was the reason!

**Comment by Stonie70** [comment]
Great Support !

**Comment by mdaskalov** [comment]
Thanx. I’ve added a check in the new release to parse only when the http status is 200.
