### ISSUE TITLE
Channel Reference

### ISSUE THREAD

**Issue by Stonie70** [mdaskalov/homebridge-dreambox#33]
Hi, one more question:
How do I get the: ref - Channel reference as in the bouquet file ?
Thank you.

**Comment by mdaskalov** [comment]
you can have a look in the bouquet file under:
```
/etc/enigma2/userbouquet.favourites.tv
```
or use curl to query the current channel:
```
curl https://dm900/web/getcurrent
```
you can also get it from the „Informationen / Kanal“ menu

**Comment by Stonie70** [comment]
Great, thanks. 
And please can you give me an example how I can create more than one channel button ?

**Comment by mdaskalov** [comment]
you should install and use [Homebridge Config UI X](https://github.com/oznu/homebridge-config-ui-x) for this.
Of course you can edit the config file. Here is an example:
```
            "channels":[
                {
                    "name": "arte HD",
                    "ref": "1:0:19:283E:3FB:1:C00000:0:0:0:"
                },
                {
                    "name": "ORF1",
                    "ref": "1:0:19:132F:3EF:1:C00000:0:0:0:"
                },
                {
                    "name": "ORF2",
                    "ref": "1:0:19:1330:3EF:1:C00000:0:0:0:"
                }
            ],
```
consider giving me a star for the time...

**Comment by Stonie70** [comment]
Thank you !
