### ISSUE TITLE
MQTT does not send messages

### ISSUE THREAD

**Issue by Lling** [mdaskalov/homebridge-dreambox#34]
Hi!
I wanted to test the MQTT Feature today but something is wrong. I would say it is something on my side. 

This is my homebridge config for the plugin:
` {
            "devices": [
                {
                    "name": "Dreambox",
                    "hostname": "192.168.1.252",
                    "port": 80,
                    "username": "root",
                    "bouquet": "HD (TV)",
                    "updateInterval": 30,
                    "offWhenUnreachable": false,
                    "mqttTopic": "dreambox"
                }
            ],
            "deviceType": "TV_SET_TOP_BOX",
            "mqtt": true,
            "mqttBroker": "192.168.1.29",
            "platform": "Dreambox"
        }`

But on my mqtt tool i didn't see anything when i'm subscribed to "dreambox/state/power" or "dreambox/state/channel".
Also in the logfile I don't see any message that anything is sent.

Could you give me a tip?

**Comment by mdaskalov** [comment]
Actually this is meant for the GP4 [mqtt-plugin](https://www.i-have-a-dreambox.com/wbb5/forum/index.php?thread/198501-mqtt-plugin/&postID=2228621#post2228621) which publishes the updates.

I don't know if there is an alternative, and if you can install it in other images.

In my latest release you can define polling interval which actually makes the same (but keeps your homebridge server busy).

**Comment by Lling** [comment]
Ok thanks. That is the problem, i think. This plugin doesn't work with my openATV OS. Thanks for your help anyway.
