### ISSUE TITLE
Devices will not be displayed in home+

### ISSUE THREAD

**Issue by DocUltra** [mdaskalov/homebridge-dreambox#36]
Hi, do sbd know, why does the Device not be displayed in home+?

**Comment by mdaskalov** [comment]
What do you mean with home+?

**Comment by Lling** [comment]
Home+ is another app to controll homekit stuff.
And i think thats a problem of home+ and not of the plugin.

**Comment by mdaskalov** [comment]
The eve app is also not showing the Dreambox as device. Write to the app support...
