### ISSUE TITLE
No more connection after audit fix

### ISSUE THREAD

**Issue by tukkatakka** [mdaskalov/homebridge-dreambox#39]
Hello,
I have performed after the update of homebridge-dreambox "audit fix". Since then I no longer get a connection to the Dreambox. In the homebridge log now comes the following message: 
-getPowerState: callEnigmaWebAPI: http://User:Password@IP-Adress/web/powerstate is an url with embedded credentails.

Maybe someone has a solution for this?
Reinstalling homebridge-dreambox did not help
The URL link is of course filled in with user and password on my homebridge

Thanks

**Comment by mdaskalov** [comment]
Should be fixed in release 2.2.0 - the credentials are now submitted using request headers.
