### ISSUE TITLE
powerstate detection not working properly

### ISSUE THREAD

**Issue by btk999** [mdaskalov/homebridge-dreambox#7]
Hi,

i have a dreambox800 with openATV installed and in my case http://dm800se/web/powerstate returns:

<e2powerstate>
<e2instandby> true </e2instandby>
</e2powerstate>

So....:
[Dreambox] callEnigmaWebAPI response: {
  "e2powerstate": {
    "e2instandby": "\nfalse\t"
  }
}

Therefore i changed a line in getPowerState(callback) as hotfix:

          this.powerState = res.e2powerstate.e2instandby === '\nfalse\t';

But i think there is a better way.
Maybe it makes sense to switch over to
dreamboxurl/API instead of using dreamboxurl/web?

With the API you get proper json directly. E.g.:

{
 "instandby": true, 
 "result": true
}

Best regards :)

**Comment by mdaskalov** [comment]
The OpenWebif API should be backward compatible with the enigma webinterface API.
The problem is the whitespace which was obviously preserved by `xml2js`.
I've pushed new release v0.4.2 which should fix this. 
Please upgrade and let me know if this helps.
Unfortunately I can't test it as I have the original dream software installed.

**Comment by btk999** [comment]
Thanks for the quick fix, working perfect now!

**Comment by btk999** [comment]
Thanks, working perfect 😊

I closed the issue.

One more question: Do you know if it will be possible to control TV Channels with SIRI in future?

Right now it can just be controlled in the Home App and not with siri, right?

 

Best regards

Philip

 

Von: Milko Daskalov <notifications@github.com> 
Gesendet: Dienstag, 31. März 2020 21:45
An: mdaskalov/homebridge-dreambox <homebridge-dreambox@noreply.github.com>
Cc: btk999 <botkill@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [mdaskalov/homebridge-dreambox] powerstate detection not working properly (#7)

 

The OpenWebif API should be backward compatible with the enigma webinterface API.
The problem is the whitespace which was obviously preserved by xml2js.
I've pushed new release v0.4.2 which should fix this.
Please upgrade and let me know if this helps.
Unfortunately I can't test it as I have the original dream software installed.
