### ISSUE TITLE
por webif

### ISSUE THREAD

**Issue by hugohuetor** [mdaskalov/homebridge-dreambox#9]
I could enter webif port number, I have it changed and cannot connect

**Comment by mdaskalov** [comment]
Yeah, you’re right. Currently only the hostname could be configured. I will change this to endpoint (http://<dream_ip>:<port>) in next release. Please use port 80 for now.

Von: hugohuetor<mailto:notifications@github.com>
Gesendet: Samstag, 25. April 2020 22:05
An: mdaskalov/homebridge-dreambox<mailto:homebridge-dreambox@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Betreff: [mdaskalov/homebridge-dreambox] por webif (#9)


I could enter webif port number, I have it changed and cannot connect

**Comment by mdaskalov** [comment]
Yeah, you’re right. Currently only the hostname could be configured. I will change this to endpoint (`http://<dream_ip>:<port>`) in next release. Please use port `80` for now.

**Comment by hugohuetor** [comment]
Thank you

**Comment by mdaskalov** [comment]
Resolved in v0.4.4
